### ISSUE TITLE
Socket.set*Timeout does not work

### ISSUE THREAD

**Issue by elliott-miller** [niwinz/jnanomsg#16]
Given this code:

```java
ReqSocket socket = new ReqSocket();
socket.setRecvTimeout(2000);
socket.connect("tcp://localhost:5555");
socket.send("Something");
socket.recvString();
```

I would expect the ```socket.recvString();``` to timeout after 2 seconds (assuming there is nothing listening on localhost:5555). Instead it blocks forever.

It seems that the underlying code..

```java
NativeLibrary.nn_setsockopt(socket, Nanomsg.constants.NN_SOL_SOCKET,
                                Nanomsg.constants.NN_RCVTIMEO, newSizeT(milis), Native.SIZE_T_SIZE);
```

Does not work as it passes a long, nanomsg expects an int for NN_RCVTIMEO. I have confirmed this with this c code which fails:

```c
long timeout = 2000;
assert( nn_setsockopt (sock, NN_SOL_SOCKET, NN_RCVTIMEO, &timeout, sizeof(timeout)) >=0 );
```

This works:

```c
int timeout = 2000;
assert( nn_setsockopt (sock, NN_SOL_SOCKET, NN_RCVTIMEO, &timeout, sizeof(timeout)) >=0 );
```

I am not familiar with jna, but this seems to work:

```java
IntByReference receiveTimeout = new IntByReference(2000);
    NativeLibrary.nn_setsockopt(socket, Nanomsg.constants.NN_SOL_SOCKET, Nanomsg.constants.NN_RCVTIMEO, receiveTimeout.getPointer(), 4);
```

Thanks

**Comment by rahulpowar** [comment]
Seeing the same thing. The alternative `NativeLibrary.nn_setsockopt ` work around presented above works.

**Comment by niwinz** [comment]
That should be fixed in the last version.

Thanks to both!
