### ISSUE TITLE
When is the next release planned (v0.4.3+)?

### ISSUE THREAD

**Issue by deepakprabhakara** [niwinz/jnanomsg#20]
Hello,

I have updated to nanomsg 0.8-beta and need to set the NN_RCVMAXSIZE option since the recv buffer is now only 1MB by default.

Is there a new release planned?

Regards.
Deepak Prabhakara.

**Comment by niwinz** [comment]
No new release is planned because the future of nanomsg is uncertain (http://sealedabstract.com/rants/nanomsg-postmortem-and-other-stories/) so I don't want waste my time on working on this. :(
